In [1]:
import numpy as np

class MatrixCalculator:

    def __init__(self, A, B):
        self.A = np.array(A)
        self.B = np.array(B)

    def addition(self):
        return self.A + self.B

    def subtraction(self):
        return self.A - self.B

    def multiplication(self):
        return np.dot(self.A, self.B)

A = [[1,2],
     [3,4]]

B = [[5,6],
     [7,8]]

calc = MatrixCalculator(A,B)

print("Matrix A:\n", calc.A)
print("Matrix B:\n", calc.B)
print("Addition:\n", calc.addition())
print("Subtraction:\n", calc.subtraction())
print("Multiplication:\n", calc.multiplication())

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[19 22]
 [43 50]]
