In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [2]:
arr = np.random.rand(5)
print(arr)

[0.86012    0.84644204 0.1123798  0.14686599 0.62894957]


In [3]:
arr = np.array([10,20,30,40,50])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951


In [4]:
arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]
