In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


In [2]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

C = A + B

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Addition:\n", C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Addition:
 [[ 6  8]
 [10 12]]
