In [1]:
import numpy as np

a = np.zeros((3,3))
b = np.ones((2,4))
c = np.arange(1,10)

print("Zeros array:\n", a)
print("Ones array:\n", b)
print("Arange array:", c)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Arange array: [1 2 3 4 5 6 7 8 9]


In [2]:
arr = np.arange(1,10)

reshaped = arr.reshape(3,3)

print("Original Array:", arr)
print("Reshaped Array:\n", reshaped)

Original Array: [1 2 3 4 5 6 7 8 9]
Reshaped Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr = np.array([10,20,30,40,50])

print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice:", arr[1:4])

First element: 10
Last element: 50
Slice: [20 30 40]
