In [40]:
#numpy 
# ARRAY ATTRIBUTES
import numpy as A

A.ones((3,3),dtype=str) 
# to generate array of RXC 
# object.zeros((row,col),dtype='int)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [4]:
A.zeros((3,3),dtype='str')

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [5]:
A.eye(5)  # I  identity  

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
A.arange(5,10,1)
# syntax 
#obj.arange(start,end,step)


array([5, 6, 7, 8, 9])

In [9]:
#linespace 
# syntax 
# obj.linespace(start,end,no)

A.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [15]:
Arr_int=A.arange(0,15,1)
print(Arr_int)
print()
print(Arr_int.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

1


In [17]:
# Reshaping the array 
# syntax array_name.reshape(row,col)

two_D_arr=Arr_int.reshape(5,3)
print(two_D_arr)
print(two_D_arr.ndim)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
2


In [20]:
arr_3=A.arange(0,12)
print(arr_3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [23]:
array_c=arr_3.reshape(3,2,2)
print(array_c)
print()
print(array_c.ndim)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]

3


In [ ]:
# syntax for reshaping 

# variable=arr_name.reshape(arrno,no_row,no_col)

In [25]:
CSE=A.arange(0,15)
print(CSE)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [27]:

print(CSE[7:])

[ 7  8  9 10 11 12 13 14]


In [50]:
CSE

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
print(CSE[5:14:3])

[ 5  8 11]


In [53]:
CSE

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
print(CSE[-3])

12


In [ ]:
# mathematical operations 
#+ - * / 
Arr_one=A.arange(0,4)
print(Arr_one)
Arr_two=A.arange(5,9)
print(Arr_two)
print('adition is ')
print(Arr_one-Arr_two)


[0 1 2 3]
[5 6 7 8]
adition is 
[-5 -5 -5 -5]


In [42]:
car=A.arange(0,11,2)
car

array([ 0,  2,  4,  6,  8, 10])

In [43]:
car>5

array([False, False, False,  True,  True,  True])

In [44]:
car<4

array([ True,  True, False, False, False, False])