In [1]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951


In [2]:
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Matrix:\n", matrix)
print("Shape:", matrix.shape)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [3]:
import numpy as np

random_array = np.random.randint(1, 100, size=5)

print("Random Numbers:", random_array)

Random Numbers: [ 3 67 71 40 47]
