In [2]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

C = np.dot(A,B)
print(C)

[[19 22]
 [43 50]]


In [3]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

C = A + B
print(C)

[[ 6  8]
 [10 12]]


In [4]:
arr = np.array([4,7,2,9,1])

print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Maximum: 9
Minimum: 1


In [5]:
arr = np.array([9,4,6,2,1])

sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 4 6 9]
