In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [2]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.flatten())

[1 2 3 4 5 6]


In [3]:
A = np.array([1,2,3])
B = np.array([4,5,6])

print(A * B)

[ 4 10 18]


In [4]:
arr = np.array([1,2,2,3,4,4,5])

print(np.unique(arr))

[1 2 3 4 5]


In [6]:
#Finding Index of Maximum Value
arr = np.array([3,7,1,9,4])

print(np.argmax(arr))

3
