In [1]:
import numpy as np

arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
arr = np.arange(2, 21, 2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [3]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [5]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(arr[2])

30
